package:
  name: 'nionswift-eels-analysis'
  version: '0.6.13'

source:
  git_rev: 0.6.13
  git_url: https://github.com/nion-software/eels-analysis.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.12
    - nionswift >=16.16,<17.0
    - nionui >=10.2,<11.0
    - numpy >=2.0,<3.0

test:
  imports:
    - nion.eels_analysis
    - nion.eels_analysis.test
    - nionswift_plugin.nion_eels_analysis
    - nionswift_plugin.nion_eels_analysis.test

about:
  home: https://github.com/nion-software/eels-analysis
  license: GPL-3.0
  summary: "Library and UI for doing EELS analysis with Nion Swift."
  description: "Library and UI for doing EELS analysis with Nion Swift."

extra:
  recipe-maintainers:
    cmeyer
